"""Assemble the final v2-sonnet dataset asset from annotated rows + judge outcomes (t0014).

Reads `_outputs/v2_sonnet_annotated.jsonl` and `_outputs/v2_sonnet_judge_outcomes.jsonl`, joins
judge verdicts into the corresponding annotated rows by `_pilot_row_index`, and writes the
consolidated dataset asset under `assets/dataset/hierarchical-annotation-v2-sonnet/`.

Also writes:
- `details.json` per the dataset asset spec (v2)
- `description.md` with the seven mandatory sections
"""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path
from typing import Any

from tasks.t0014_v2_annotator_sonnet_rerun.code.constants import (
    ANNOTATOR_MODEL_ID,
    DATASET_CATEGORIES,
    JUDGE_MODEL_ID,
)
from tasks.t0014_v2_annotator_sonnet_rerun.code.paths import (
    DATASET_ASSET_DIR,
    DATASET_DESCRIPTION_MD,
    DATASET_DETAILS_JSON,
    DATASET_FILES_DIR,
    V2_SONNET_FINAL_JSONL,
    V2_SONNET_JUDGE_OUTCOMES_PATH,
    V2_SONNET_RAW_OUTPUT,
)


def _load_jsonl(*, path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def _build_judge_index(*, outcomes: list[dict[str, Any]]) -> dict[int, dict[str, Any]]:
    index: dict[int, dict[str, Any]] = {}
    for outcome in outcomes:
        idx = outcome.get("pilot_row_index")
        if isinstance(idx, int):
            index[idx] = outcome
    return index


def merge_and_write_jsonl() -> dict[str, Any]:
    annotated = _load_jsonl(path=V2_SONNET_RAW_OUTPUT)
    outcomes = (
        _load_jsonl(path=V2_SONNET_JUDGE_OUTCOMES_PATH)
        if V2_SONNET_JUDGE_OUTCOMES_PATH.exists()
        else []
    )
    judge_index = _build_judge_index(outcomes=outcomes)

    DATASET_FILES_DIR.mkdir(parents=True, exist_ok=True)

    rows_acceptable = 0
    rows_needs_revision = 0
    rows_judged = 0
    rows_complete = 0

    with V2_SONNET_FINAL_JSONL.open("w", encoding="utf-8") as f:
        for row in annotated:
            idx = row.get("_pilot_row_index")
            outcome = judge_index.get(idx) if isinstance(idx, int) else None
            if outcome is not None:
                row["judge_verdict"] = outcome.get("verdict")
                row["judge_notes"] = outcome.get("justification") or outcome.get("notes")
                if row["judge_verdict"] == "acceptable":
                    rows_acceptable += 1
                    rows_judged += 1
                elif row["judge_verdict"] == "needs revision":
                    rows_needs_revision += 1
                    rows_judged += 1
            if row.get("hierarchy_completeness"):
                rows_complete += 1
            f.write(json.dumps(row, ensure_ascii=False))
            f.write("\n")

    return {
        "rows_total": len(annotated),
        "rows_complete": rows_complete,
        "rows_judged": rows_judged,
        "rows_acceptable": rows_acceptable,
        "rows_needs_revision": rows_needs_revision,
    }


def write_details_json(*, summary: dict[str, Any]) -> None:
    details = {
        "spec_version": "2",
        "dataset_id": "hierarchical-annotation-v2-sonnet",
        "name": "Hierarchical Annotation v2-sonnet (115-row pilot, tree schema, sonnet annotator)",
        "version": "v2-sonnet",
        "short_description": (
            "Sonnet-annotator re-run of the v2 tree-shaped hierarchical annotation of 115 "
            "benchmark tasks (FrontierScience-Olympiad, SWE-bench Verified, WorkArena++, "
            "tau-bench). Re-annotates the v1 pilot rows under the v2 tree schema with "
            "claude-sonnet-4-6 (haiku in t0009), keeping prompt and judge held constant. "
            f"Includes a {summary['rows_judged']}-row LLM-as-judge spot-check on the same "
            "23-row stratified sample as t0009 (seed=42)."
        ),
        "description_path": "description.md",
        "source_paper_id": None,
        "url": None,
        "download_url": None,
        "year": 2026,
        "date_published": date.today().isoformat(),
        "authors": [
            {
                "name": "Glite ARF reasoning-scale2 project",
                "country": None,
                "institution": None,
                "orcid": None,
            }
        ],
        "institutions": [],
        "license": "inherited-per-row",
        "access_kind": "restricted",
        "size_description": (
            f"{summary['rows_total']} rows total; each row carries a tree-shaped hierarchy "
            f"(global / subtasks-with-atomics / global_atomics) and a parallel gold_actions "
            f"tree, generated by claude-sonnet-4-6. {summary['rows_complete']} rows passed "
            f"the v2 hierarchy_completeness check. {summary['rows_judged']} rows received an "
            f"LLM-as-judge verdict from claude-haiku-4-5 ({summary['rows_acceptable']} "
            f"acceptable, {summary['rows_needs_revision']} needs revision)."
        ),
        "files": [
            {
                "path": "files/hierarchical_annotation_v2_sonnet.jsonl",
                "description": (
                    f"{summary['rows_total']}-row JSONL with the v2 tree schema annotated by "
                    "claude-sonnet-4-6 and judge verdicts merged into the sampled rows."
                ),
                "format": "jsonl",
            }
        ],
        "categories": DATASET_CATEGORIES,
    }
    DATASET_DETAILS_JSON.write_text(
        json.dumps(details, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def _bench_breakdown(rows: list[dict[str, Any]]) -> dict[str, dict[str, int]]:
    out: dict[str, dict[str, int]] = {}
    for row in rows:
        bench = row.get("benchmark", "")
        bucket = out.setdefault(
            bench,
            {
                "total": 0,
                "complete": 0,
                "judged": 0,
                "acceptable": 0,
                "needs_revision": 0,
            },
        )
        bucket["total"] += 1
        if row.get("hierarchy_completeness"):
            bucket["complete"] += 1
        verdict = row.get("judge_verdict")
        if verdict == "acceptable":
            bucket["acceptable"] += 1
            bucket["judged"] += 1
        elif verdict == "needs revision":
            bucket["needs_revision"] += 1
            bucket["judged"] += 1
    return out


def write_description_md(*, summary: dict[str, Any]) -> None:
    final_rows = _load_jsonl(path=V2_SONNET_FINAL_JSONL)
    breakdown = _bench_breakdown(final_rows)
    today = date.today().isoformat()
    bench_table_lines: list[str] = [
        "| Benchmark | Total rows | Complete | Judged | Acceptable | Needs revision |",
        "|-----------|------------|----------|--------|------------|----------------|",
    ]
    for bench, b in sorted(breakdown.items()):
        bench_table_lines.append(
            f"| {bench} | {b['total']} | {b['complete']} | {b['judged']} | "
            f"{b['acceptable']} | {b['needs_revision']} |"
        )
    bench_table = "\n".join(bench_table_lines)

    md = f"""---
spec_version: "2"
dataset_id: "hierarchical-annotation-v2-sonnet"
summarized_by_task: "t0014_v2_annotator_sonnet_rerun"
date_summarized: "{today}"
---

# Hierarchical Annotation v2-sonnet (115-row pilot, tree schema, sonnet annotator)

## Metadata

* **Name**: Hierarchical Annotation v2-sonnet (115-row pilot, tree schema, sonnet annotator)
* **Year**: 2026
* **Authors**: Glite ARF reasoning-scale2 project
* **License**: inherited-per-row
* **Access**: restricted
* **Size**: {summary["rows_total"]} rows total; \
{summary["rows_complete"]} pass v2 hierarchy_completeness; \
{summary["rows_judged"]} judged; {summary["rows_acceptable"]} acceptable, \
{summary["rows_needs_revision"]} needs revision.

## Overview

This dataset is a controlled re-annotation of the v1 hierarchical annotation pilot
(`tasks/t0005_hierarchical_annotation_pilot_v1/assets/dataset/hierarchical-annotation-v1/`) under
the same v2 tree schema as
`tasks/t0009_hierarchical_annotation_v2/assets/dataset/hierarchical-annotation-v2/`, but with
`{ANNOTATOR_MODEL_ID}` (sonnet) as the annotator instead of haiku. The judge stays on
`{JUDGE_MODEL_ID}` (haiku), held constant across all variants.

The purpose of this asset is to deconfound the t0009 headline result. t0009 reported a +58 pp
aggregate accept-rate gain over v1, but it changed two things at once: schema (flat -> tree) and
annotator (sonnet -> haiku). This asset isolates the model component by reusing the v2 schema with
the original v1 annotator model.

The v2 tree schema records:

* `hierarchy.global` — one-sentence top-level approach,
* `hierarchy.subtasks` — list of `{{subtask, atomics}}` objects, where each subtask carries the
  atomic steps that implement it,
* `hierarchy.global_atomics` — atomic steps that span the whole trajectory and do not belong to
  any single subtask (typically verification, sanity checks, or cross-cutting concerns).

The same shape is mirrored on the `gold_actions` side of each row, recording the resolved concrete
actions an agent would take at each level.

The v2 pass also fixes the v1 LLM-as-judge truncation bug: where v1 truncated the problem text to
the first 1,500 characters before showing it to either the annotator or the judge, v2 passes the
full `problem` body to both.

## Content & Annotation

Each row of the JSONL contains the following fields:

| Field | Type | Description |
|-------|------|-------------|
| `_pilot_row_index` | int | 0-based row index in the v1 pilot file. Unique key. |
| `task_id` | string | Source task ID; non-unique (14 v1 collisions). |
| `benchmark` | string | FrontierScience-Olympiad / SWE-bench Verified / WorkArena++ / tau-bench. |
| `domain` | string | Free-form domain tag from the source row. |
| `difficulty` | object | Difficulty rubric from the source row, copied verbatim. |
| `problem` | string | Full problem statement (no truncation). |
| `hierarchy` | object | v2 tree (`global`, `subtasks`, `global_atomics`). |
| `gold_actions` | object | Mirror tree of resolved concrete actions. |
| `annotation_model` | string | `{ANNOTATOR_MODEL_ID}`. |
| `judge_verdict` | string \\| null | `"acceptable"`, `"needs revision"`, or `null`. |
| `judge_notes` | string \\| null | Justification or error string for the verdict. |
| `hierarchy_completeness` | bool | True iff `global` is non-null AND (any subtask has \
atomics OR `global_atomics` non-empty). |
| `annotator_notes` | string | Parser status: `ok` / `parse-failure: ...` / `call-failure: ...`. |

**Sample stratification.** The judge sample was drawn with a fixed seed of 42, stratified by
benchmark to allocate 6 rows from FrontierScience-Olympiad, 6 from SWE-bench Verified, 6 from
WorkArena++, and 5 from tau-bench (totalling 23 rows, 20% of the dataset). Only rows with
`hierarchy_completeness == true` were eligible for sampling. The same seed is used by t0009, so
the resulting sample composition is directly comparable when both runs hit
`hierarchy_completeness == true` on the same `_pilot_row_index` set.

## Statistics

{bench_table}

* Total rows: {summary["rows_total"]}
* Rows with v2 `hierarchy_completeness == true`: {summary["rows_complete"]}
* Rows judged: {summary["rows_judged"]}
* Acceptable: {summary["rows_acceptable"]}
* Needs revision: {summary["rows_needs_revision"]}

## Usage Notes

* Load the JSONL with one row per line; each line is a JSON object with the schema described
  above. Use `_pilot_row_index` rather than `task_id` as the primary key — `task_id` is not
  unique across the source pilot.
* Compare against
  `tasks/t0009_hierarchical_annotation_v2/assets/dataset/hierarchical-annotation-v2/files/`
  (haiku annotator, same schema, same prompt) to isolate the annotator-model effect; compare
  against
  `tasks/t0005_hierarchical_annotation_pilot_v1/assets/dataset/hierarchical-annotation-v1/files/`
  (sonnet annotator, flat schema) to isolate the schema effect.
* Rows where `hierarchy_completeness == false` should be excluded from any downstream agent
  evaluation — their tree was not parseable at annotation time.
* Rows where `judge_verdict == "needs revision"` are still usable for downstream experiments,
  but their gold_actions should be inspected manually before being trusted as ground truth.
* The judge is a single LLM rater; treat verdicts as advisory, not as inter-rater agreement.

## Main Ideas

* **Deconfound design**: this asset and t0009's `hierarchical-annotation-v2` differ only in the
  annotator model. The v2-sonnet vs v2-haiku accept-rate delta therefore measures the
  annotator-model effect under a fixed schema and fixed judge. The v2-sonnet vs v1-sonnet delta
  measures the schema effect under a fixed annotator model.
* **Sonnet > haiku within the v2 schema** is the empirically expected outcome based on
  Boisvert2024 (Sonnet beats Haiku by ~25 pp on WorkArena++) and Zhou2022 (decomposition prompts
  +16 pp), which together suggest both axes contribute.
* **Same prompt, same temperature, same judge**: keeping every other element constant means any
  observed delta is attributable to the annotator-model swap.
* **Same 23-row sample** (seed=42, stratified): row-matched comparison enables Wilson 95% CI on
  per-benchmark deltas with n=5-6 per cell.

## Summary

Hierarchical Annotation v2-sonnet is the controlled-rerun companion to t0009's v2 dataset. It
re-annotates the same {summary["rows_total"]} benchmark rows under the same tree schema and the
same prompt, but with claude-sonnet-4-6 instead of claude-haiku-4-5. The judge is held constant on
claude-haiku-4-5 and operates on the same 23-row stratified sample, so the resulting accept-rate
delta is a clean read on the annotator-model component of t0009's +58 pp headline.

For this project, this asset is the missing arm of the {{schema, model}} 2x2: t0005 = (flat,
sonnet), t0009 = (tree, haiku), this asset = (tree, sonnet). The fourth cell (flat, haiku) is not
needed because no downstream experiment plans to use a flat schema with haiku.

Compared to alternatives — there is no published hierarchical annotation of these specific
benchmark composites; v1, v2-haiku, and v2-sonnet are bespoke project assets. WorkArena++'s
upstream paper (Boisvert2024) provides a tree-shaped annotation schema for its own subset that
v2's design echoes.
"""
    DATASET_DESCRIPTION_MD.write_text(md, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build v2-sonnet dataset asset")
    parser.parse_args()
    DATASET_ASSET_DIR.mkdir(parents=True, exist_ok=True)
    summary = merge_and_write_jsonl()
    write_details_json(summary=summary)
    write_description_md(summary=summary)
    print(
        f"Wrote {V2_SONNET_FINAL_JSONL}, {DATASET_DETAILS_JSON}, {DATASET_DESCRIPTION_MD}\n"
        f"  rows_total={summary['rows_total']}, rows_complete={summary['rows_complete']}, "
        f"rows_judged={summary['rows_judged']}, "
        f"acceptable={summary['rows_acceptable']}, "
        f"needs_revision={summary['rows_needs_revision']}"
    )


if __name__ == "__main__":
    main()


# Imports re-stated here so ruff sees them as used.
_ = JUDGE_MODEL_ID
